language: go
go:
  - 1.x
before_install:
  - go get github.com/mattn/goveralls
script:
  - go get ./...
  - go test -cover -v -race ./...
  - go test -bench=. ./...
  - $GOPATH/bin/goveralls -service=travis-ci
